### ISSUE TITLE
Testing party: 

### ISSUE THREAD

**Issue by weineng-hsu** [gcivil-nyu-org/S2022-Team-2-repo#114]
**Issue**
In the page of user profile, when user edit their profile photo and click on "clear" bottom, it will have ValueError at /dashboard/.
Error message: The 'image' attribute has no file associated with it. 

****
We had similar bug. You could check the image field has this extra argument. (blank=True)

**Comment by weineng-hsu** [comment]
I'm sorry. I didn't see the the part here. Really sorry for breaking the account. 
What does not work here?
The “Clear” checkbox is not yet functional. We aim to use this checkbox to delete the user uploaded image(if any) and keep the profile picture as a system defined default image.

**Comment by manektamanna** [comment]
No worries. We are still trying to figure this out. We already know this issue. Thank you for your feedback.
