### ISSUE TITLE
Testing Party

### ISSUE THREAD

**Issue by pranavsinghps1** [gcivil-nyu-org/S2022-Team-2-repo#129]
* Logging for User 2 yielded the following error

<img width="1440" alt="Screenshot 2022-04-17 at 6 51 42 PM" src="https://user-images.githubusercontent.com/46050869/163735814-c5c5e180-cb76-4e1c-b980-38b3ff3d7ba8.png">

* The Clear option seems to work fine if we change the picture and then save, but just checking it without changing the picture throws an error.
* My friend's option doesn't seem to work.[tested using other IDs than User2]

<img width="1440" alt="Screenshot 2022-04-17 at 6 57 23 PM" src="https://user-images.githubusercontent.com/46050869/163735998-1d282fe6-647a-40a4-9f0a-ea6edd6e358e.png">

* Resizing seems to make the Navbar disappear only a violet 'circle' appears at the top right instead of the User picture, which expands the menu but the menu overlaps with the lefthand-side bar components. 
<img width="697" alt="Screenshot 2022-04-17 at 7 22 59 PM" src="https://user-images.githubusercontent.com/46050869/163735960-db157201-b552-4e34-9989-f316b91853bd.png">

**Comment by manektamanna** [comment]
You are getting Value Error because you unknowingly broke the user profile by doing something that was not to be tested. Most probably I guess you used the clear check box on the update profile page. The clear checkbox was not to be tested as of now.

We are still working on UI.
