### ISSUE TITLE
As an admin, I want to maintain the database so that the data received is accurate and relevant.

### ISSUE THREAD

**Issue by reganbragg** [gcivil-nyu-org/S2022-Team-2-repo#5]
**User story**
This user story is for the Administrator persona. The admin has read/write access of the database and can add, modify and delete users. As part of this story, we also create the database model for our application and define it's architecture and usage for each table.

**Acceptance criteria**
This user story is complete only when the entire application is complete and the admin has access to modify all the relevant models and fields.

**Definition of Done**

**Comment by DarylTC** [comment]
Planning poker score (0, 0.5, 1, 2, 3): 1
