### ISSUE TITLE
As a user, I want to be able to delete my profile, so that I no longer have an account to maintain.

### ISSUE THREAD

**Issue by ts4044** [gcivil-nyu-org/S2022-Team-2-repo#8]
**User story**
User profile creation, update and deletion are some of the most basic features of any user serving applications. Here, the story captures the requirements of such actions that the user can perform.

**Acceptance criteria**
When the user is successfully able to create their profiles using the signup feature, login to the application using the login feature and be able to delete their profile by requesting a deletion, this story will be complete.

**Definition of Done**
When all the features mentioned above are complete.

**Comment by DarylTC** [comment]
Planning Poker (0, 0.5, 1, 2, 3): 2

**Comment by ts4044** [comment]
This task is 75% complete. The deletion of profile for users is remaining.
